version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
  app:
    build: .
    container_name: node-mongo-app
    environment:
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/user-account?authSource=admin
    ports:
      - 4000:4000
    depends_on:
      - mongodb
volumes:
  mongo-data:
    driver: local